
```{r}
library(tidyverse)
library(lubridate)
library(feasts)
library(fpp3)
library(scales)
library(imputeTS)
library(tseries)
library(forecast)
library(TSstudio)
Sys.setlocale("LC_TIME", "C")
```

```{r}
raw_data <- read.csv("Dane/PJME_hourly.csv")

ts_data <- raw_data %>%
  rename(datetime = Datetime) %>%
  mutate(datetime = as_datetime(datetime)) %>%
  arrange(datetime)

```

```{r}
#Sprawdzenie duplikatów
ts_data %>% duplicates(index = datetime)

#Przygotowanie danych
ts_data <- raw_data %>%
  rename(datetime = Datetime,
         h_energy_consumption = PJME_MW) %>%
  mutate(datetime = as_datetime(datetime)) %>%
  arrange(datetime) %>%
  group_by(datetime) %>% #duplikaty zastępujemy średnią z duplikatów
  summarise(h_energy_consumption = mean(h_energy_consumption, na.rm = TRUE)) %>%
  as_tsibble(index = datetime) %>%
  fill_gaps() %>% #nieliczne braki w danych uzupełniamy przy pomocy interpolacji liniowej
  mutate(h_energy_consumption = na_interpolation(h_energy_consumption))
```


```{r}
#Wykres ogólny
autoplot(ts_data, h_energy_consumption) +
  labs(title = "Hourly Energy Consumption",
       subtitle = "PJM East Region: 2001-2018 (PJME)",
       x = "Datetime",
       y = "Energy Consumption (MW)") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 20, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 16, hjust = 0.5),
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    axis.text = element_text(size = 12),
    plot.caption = element_text(size = 10),
    panel.grid.major = element_line(color = "grey80"),
    panel.grid.minor = element_line(color = "grey90"),
    plot.background = element_rect(fill = "white"),
    panel.background = element_rect(fill = "white")
  ) +
  scale_x_datetime(date_labels = "%Y-%m-%d", date_breaks = "5 years") +
  scale_y_continuous(labels = scales::comma)
```

```{r}
#Sezonowość roczna
ts_data %>% 
  gg_season(h_energy_consumption, labels = "both") +
  labs(title = "Hourly Energy Consumption",
       x = "Datetime",
       y = "Energy Consumption (MW)")
```

```{r}
#Sezonowość tygodniowa
ts_data %>% 
  gg_season(h_energy_consumption, period = "week") +
  theme(legend.position = "none") +
  labs(title = "Hourly Energy Consumption",
       x = "Datetime",
       y = "Energy Consumption (MW)")
```

```{r}
#Sezonowość dzienna
ts_data %>% 
  gg_season(h_energy_consumption, period = "day") +
  theme(legend.position = "none") +
  labs(title = "Hourly Energy Consumption",
       x = "Datetime",
       y = "Energy Consumption (MW)")

```

```{r}
#test ADF
adf.test(as.ts(ts_data))
```
```{r}
#modelowanie ARIMA/SARIMA funkcją auto.arima + prognoza naiwna
tomodel <- as.ts(ts_data)
prog <- naive(tomodel, h = 336) #na następne 2 tygodnie
accuracy(prog)
fit <- auto.arima(ts_data, stepwise=TRUE, nmodels=10) #max 10 modeli bo zajmuje bardzo dużo czasu
checkresiduals(fit)
```

```{r}
#prognoza wg autoarimy
accuracy(fit)
fcast <- forecast(fit, h = 336)

toshow <- window(tomodel, start=8044)


autoplot(toshow, axis.text.x = FALSE) +
  autolayer(fcast[[4]], series = "Forecast") +
  labs(title = "Forecast of Hourly Energy Consumption",
       y = "Energy Consumption (MW)") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
#chowam oś X bo autoarima zepsuła mi indeksy czasu


```




