


```{r}
library(dplyr)
library(readr)
library(httr)
library(rvest)
library(lubridate)
library(forecast)
library(ggplot2)
library(tseries)
library(forecast)
library(grid)
library(scales)
```
```{r}
current_dir <- getwd()
folder_path <- file.path(current_dir, "Dane")
files <- list.files(path = folder_path, pattern = "*.csv", full.names = TRUE)
print(folder_path)
```


```{r}
#Ładowanie danych i dopisanie dat z poszczególnych nazw plików, 
#mamy dużo danych pogrupowanych per miasto ale rozdzielone na kilka plików

all_data <- list()

# Przeszukaj każdy plik CSV w folderze, który zaczyna się od "apartments_pl"
files <- list.files(path = folder_path, pattern = "apartments_pl*", full.names = TRUE)

for (file in files) {

  file_name <- basename(file)
  
  # EWyciągnij date z pliku
  date_str <- sub("apartments_pl_(\\d{4})_(\\d{2})\\.csv", "\\1.\\2", file_name)
  

  data <- read.csv(file)
  
  data$date <- as.Date(paste0(date_str, ".01"), format = "%Y.%m.%d")
  

  all_data[[file_name]] <- data
}

combined_data <- do.call(rbind, all_data)


print(combined_data)

```
```{r}
#Podstawowe sprawdzenie danych
sales_data = combined_data

head(sales_data)
tail(sales_data)
dim(sales_data)
str(sales_data)


```
```{r}
sales_data$date <- as.Date(sales_data$date, format = "%Y-%m-%d")

sales_data <- sales_data %>% arrange(date)


head(sales_data)
ts_sales_data <- ts(sales_data$price, start = c(2023,8), end = c(2024,5), frequency = 12)

plot(ts_sales_data, main = "Ceny mieszkań w czasie", ylab = "Cena", xlab = "Miesiąc")

adf_test <- adf.test(ts_sales_data) 
```
```{r}
print(count(sales_data))
```
```{r}
split_by_city <- function(sales_data, city) {
  if (!city %in% names(sales_data)) {
    stop("Error: City column not found in the dataframe.")
  }
  
  cities <- unique(data[, city])
  
  city_dataframes <- list()
  
for (city in cities) {
  city_dataframe <- sales_data[sales_data$city == city, ] 
  city_dataframes[[city]] <- city_dataframe
}
  
  return(city_dataframes)
}

```

```{r}
#Fuinkcja zwraca dane dla konkretnego miasta
city_dataframes <- split_by_city(sales_data, "city")
szczecin_data <- city_dataframes[["szczecin"]]
print(head(szczecin_data))
print(tail(szczecin_data))
```
```{r}

# Wrap your plotting code in a function
plot_city_prices <- function(city, data) {
  ggplot(data[data$city == city, ], aes(x = date, y = price)) +
    geom_line() +
    labs(title = paste0("Ceny mieszkań w ", city)) 
    theme(plot.width = 10, plot.height = 6)
}

# Apply the function to each city using lapply
city_plots <- lapply(unique(sales_data$city), plot_city_prices, sales_data)

# Print the plots (requires additional packages for interactive viewing)

grid.arrange(grobs = city_plots, nrow = nrow(city_plots))  # Adjust nrow if needed
```

```{r}
plot_city_prices <- function(city, data) {

  city_plot <- ggplot(data[data$city == city, ], aes(x = date, y = price)) +
               geom_line() +
               scale_y_continuous(labels = comma) + 
               labs(title = paste0("Ceny mieszkań w ", city),
                    x = 'Data',
                    y = 'Cena')

  city_plot_grob <- ggplotGrob(city_plot)
  return(city_plot_grob)
}

city_plots <- lapply(unique(sales_data$city), plot_city_prices, sales_data)

for (plot in city_plots) {
  grid.newpage()  
  grid.draw(plot) 
}

```



```{r}
aggregate_data <- function(data) {
  data %>%
    group_by(city, month = floor_date(date, "month")) %>%
    summarise(avg_price = mean(price, na.rm = TRUE)) %>%
    ungroup()
}

# Function to plot city prices with average line and smoothed trend
plot_city_prices <- function(city, data) {
  city_data <- data[data$city == city, ]
  avg_price <- mean(city_data$avg_price, na.rm = TRUE)
  
  city_plot <- ggplot(city_data, aes(x = month, y = avg_price)) +
               geom_line() +
               geom_hline(yintercept = avg_price, linetype = "dashed", color = "red") +  # średnia cena w całym okresie
               geom_smooth(method = "loess", color = "blue", se = FALSE) +  # linia trendu wygładzona
               scale_y_continuous(labels = comma) + #format osi 
               labs(title = paste0("Ceny mieszkań w ", city),
                    x = 'Data',
                    y = 'Średnia cena') +
               annotate("text", x = min(city_data$month), y = avg_price, label = paste("Średnia cena:", comma(avg_price)), hjust = 0, vjust = -1)
  
  city_plot_grob <- ggplotGrob(city_plot)
  return(city_plot_grob)
}


# Aggregacja danych per miasto 
aggregated_data <- aggregate_data(sales_data)

city_plots <- lapply(unique(aggregated_data$city), plot_city_prices, aggregated_data)

for (plot in city_plots) {
  grid.newpage()  
  grid.draw(plot) 
}
```


```{r}
# Dopasowanie modelu ARMA, tutaj chyba coś spierdoliłem Proszę poprawić
fit <- auto.arima(ts_sales_data, stepwise = FALSE, ic = "aic")
summary(fit)
autoplot(fit)
forecasted <- forecast(fit, n.ahead = 4) 

autoplot(forecasted) +
  labs(title = "Prognoza cen mieszkań w Polsce", x = "Data", y = "Cena")

checkresiduals(fit)

accuracy(fit)
```
```{r}
print(ts_sales_data)
```


```{r}




