name: Build LaTeX document

on:
  push:
    paths:
      - .github/workflows/latex.yml
      - raport/raport.tex

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: raport/raport.tex

      - name: List directory contents after compilation
        run: ls -R

      - name: Commit and push generated PDF
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git add raport.pdf
          git commit -m "Add generated PDF"
          git push

      - name: Upload PDF file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: raport.pdf

          